### PR TITLE
[Fix Bug] Correct logic to calculate pincode and districts.

### LINKED ISSUE #1: [Bug] Giving incorrect number of pincodes for state ASSAM.
Current version of the application is showing some miscalculation of total number of pincodes for state ASSAM.

**Current output :** ASSAM has 408 pincodes and 34 districts

**Expected output :** ASSAM has 577 pincodes and 34 districts

### PR DESCRIPTION
**Pull request by muhafiz5814**
Fixes #1 

Updated the logic of event listener to get correct number of pincodes and districts.

### CODE REVIEW

File: script.js [hunk 1]
```diff
@@ -17,19 +17,30 @@ stateSelector.addEventListener("change", async (e) => {
...
-    try {
-        const response = await fetch(`${BASE_URL}?api-key=${KEY}&format=json&limit=1000&filters%5Bstatename%5D=${state}`);
-        const data = await response.json();
-
-        for (const record of data.records) {
-            totalPincodes.add(record.pincode);
-            totaDistricts.add(record.district);
-        }
+    let offset = 0;
+    const LIMIT = 1000;
```
Comment (muhafiz5814) [inline script.js:21]: Remove the below blank line.

File: script.js [hunk 2]
```diff
@@ -17,19 +17,30 @@ stateSelector.addEventListener("change", async (e) => {
...
+            const data = await response.json();
+            
+            for (const record of data.records) {
+                totalPincodes.add(record.pincode);
+                totaDistricts.add(record.district);
+            }
+
+            if (data.count < LIMIT) allFetched = true;
+            
+            offset += LIMIT;
```
Comment (muhafiz5814) [inline script.js:35]: remove extra blank lines from here.

**Review by muhafiz5814 — COMMENTED** [review]
Please do the following changes.

**Comment by muhafiz5814** [comment]
Please also make the message paragraph to show `Loading...` message while the server is fetching data from third party API and calculating output.

**Comment by muhafiz5814** [comment]
Please also make the message paragraph to show `Loading...` message while the server is fetching data from third party API and calculating output.

File: script.js [hunk 3]
```diff
@@ -17,19 +17,30 @@ stateSelector.addEventListener("change", async (e) => {
...
-
-        for (const record of data.records) {
-            totalPincodes.add(record.pincode);
-            totaDistricts.add(record.district);
-        }
+    let offset = 0;
+    const LIMIT = 1000;
+    let allFetched = false;
+
+    do {
```
Comment (muhafiz5814) [inline script.js]: `while` loop can be used here instead of `do-while` as `allFetched` is always false before this loop runs for the first time.

**Review by muhafiz5814 — COMMENTED** [review]
Please do the required changes.

File: script.js (hunk 2 above)
Comment (muhafiz5814) [reply script.js:35]: Changes have been made in commit 67a1fb0

**Comment by muhafiz5814** [comment]
> Please also make the message paragraph to show `Loading...` message while the server is fetching data from third party API and calculating output.

`Loading...` message have been added in commit ee19614

File: script.js (hunk 3 above)
Comment (muhafiz5814) [reply script.js]: This change have been made in commit 96dc800

Comment (muhafiz5814) [reply script.js]: Great work!

**Comment by muhafiz5814** [comment]
Great work @muhafiz5814 ! 
Application now seems to work in expected way.
Merging the PR now.

**Comment by muhafiz5814** [comment]
Great work @muhafiz5814 !
Application now seems to work in expected way.
Merging the PR now.
